name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
      - name: Start dependencies
        run: docker compose up -d zookeeper kafka redis

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run coverage
        run: npm run test:cov

      - name: Build Docker images for all services
        run: |
          for service in apps/*; do
            if [ -f "$service/Dockerfile" ]; then
              name=$(basename $service)
              docker build -t $name -f $service/Dockerfile .
            fi
          done
